{"name": "test_04", "status": "broken", "statusDetails": {"message": "Exception: Промокод применён повторно — ошибка", "trace": "selenium = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f56d6f9b08d6990106d2eec6a4e78151\")>\n\n    @allure.description(\"Проверка повторного применения промокода\")\n    def test_04(selenium):\n        driver = selenium\n    \n        with allure.step(\"Добавление пиццы в корзину и переход на страницу оформдения заказа\"):\n            main_p = MainPage(driver)\n            main_p.select_pizza()\n            main_p.go_to_cart()\n            main_p.order_product()\n    \n        with allure.step(\"Переход в раздел мой аккаунт\"):\n            account_p = MyAccount(driver)\n            account_p.go_my_account()\n    \n        with allure.step(\"Авторизация пользователя\"):\n            account_p.authorization()\n    \n        with allure.step(\"Переход в корзину\"):\n            main_p.go_to_cart()\n    \n        with allure.step(\"Применение промокода\"):\n            cart_p = Cart(driver)\n            time.sleep(1)\n            cart_p.apply_right_promo()\n    \n        with allure.step(\"Оформить заказ\"):\n            cart_p.order()\n    \n        with allure.step(\"Оформление заказа\"):\n            checkout_p = Checkout(driver)\n            checkout_p.checkout()\n            time.sleep(5)\n    \n        with allure.step(\"Повторный выбор пиццы\"):\n            main_p = MainPage(driver)\n            main_p.select_pizza()\n            main_p.go_to_cart()\n    \n        with allure.step(\"Повторное применение промокода\"):\n            cart_p.apply_right_promo()\n>           cart_p.promocode_assert()\n\ntests\\test_promocode.py:107: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\cart.py:90: in promocode_assert\n    self.promocode_assertion(self.cupon_apply_right, \"Coupon code applied successfully.\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.cart.Cart object at 0x000001B141EC5E50>, locator = ('xpath', '//div[@class=\"woocommerce-message\"]')\nerror_text = 'Coupon code applied successfully.'\n\n    def promocode_assertion(self, locator, error_text):\n        \"\"\"Проверка, что промокод не был применён повторно\"\"\"\n        element = self.wait.until(EC.visibility_of_element_located(locator))\n        actual_text = element.text\n        if actual_text == error_text:\n>           raise Exception(\"Промокод применён повторно — ошибка\")\nE           Exception: Промокод применён повторно — ошибка\n\nbase\\base_page.py:36: Exception"}, "description": "Проверка повторного применения промокода", "steps": [{"name": "Добавление пиццы в корзину и переход на страницу оформдения заказа", "status": "passed", "steps": [{"name": "Выбор пиццы", "status": "passed", "start": 1753716612094, "stop": 1753716616985}, {"name": "Переход в корзину", "status": "passed", "start": 1753716616985, "stop": 1753716618593}, {"name": "Переход на страницу оформления заказа", "status": "passed", "start": 1753716618593, "stop": 1753716619099}], "start": 1753716612094, "stop": 1753716619099}, {"name": "Переход в раздел мой аккаунт", "status": "passed", "steps": [{"name": "Переход на вкладку Мой аккаунт", "status": "passed", "start": 1753716619099, "stop": 1753716619555}], "start": 1753716619099, "stop": 1753716619555}, {"name": "Авторизация пользователя", "status": "passed", "steps": [{"name": "Авторизация", "status": "passed", "start": 1753716619555, "stop": 1753716620338}], "start": 1753716619555, "stop": 1753716620338}, {"name": "Переход в корзину", "status": "passed", "steps": [{"name": "Переход в корзину", "status": "passed", "start": 1753716620338, "stop": 1753716621845}], "start": 1753716620338, "stop": 1753716621845}, {"name": "Применение промокода", "status": "passed", "steps": [{"name": "Ввод верного промокода", "status": "passed", "start": 1753716622846, "stop": 1753716623277}], "start": 1753716621845, "stop": 1753716623277}, {"name": "Оформить заказ", "status": "passed", "steps": [{"name": "Перейти к оплате", "status": "passed", "start": 1753716623277, "stop": 1753716625265}], "start": 1753716623277, "stop": 1753716625265}, {"name": "Оформление заказа", "status": "passed", "steps": [{"name": "Оформление заказа, ввод данных", "status": "passed", "start": 1753716625265, "stop": 1753716627987}], "start": 1753716625265, "stop": 1753716632987}, {"name": "Повторный выбор пиццы", "status": "passed", "steps": [{"name": "Выбор пиццы", "status": "passed", "start": 1753716632988, "stop": 1753716636795}, {"name": "Переход в корзину", "status": "passed", "start": 1753716636795, "stop": 1753716638243}], "start": 1753716632988, "stop": 1753716638243}, {"name": "Повторное применение промокода", "status": "broken", "statusDetails": {"message": "Exception: Промокод применён повторно — ошибка\n", "trace": "  File \"C:\\Users\\OsmanovaF\\PycharmProjects\\PythonProject5\\tests\\test_promocode.py\", line 107, in test_04\n    cart_p.promocode_assert()\n    ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\OsmanovaF\\PycharmProjects\\PythonProject5\\pages\\cart.py\", line 90, in promocode_assert\n    self.promocode_assertion(self.cupon_apply_right, \"Coupon code applied successfully.\")\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\OsmanovaF\\PycharmProjects\\PythonProject5\\base\\base_page.py\", line 36, in promocode_assertion\n    raise Exception(\"Промокод применён повторно — ошибка\")\n"}, "steps": [{"name": "Ввод верного промокода", "status": "passed", "start": 1753716638244, "stop": 1753716638520}, {"name": "Проверка применения верного промокода", "status": "broken", "statusDetails": {"message": "Exception: Промокод применён повторно — ошибка\n", "trace": "  File \"C:\\Users\\OsmanovaF\\PycharmProjects\\PythonProject5\\pages\\cart.py\", line 90, in promocode_assert\n    self.promocode_assertion(self.cupon_apply_right, \"Coupon code applied successfully.\")\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\OsmanovaF\\PycharmProjects\\PythonProject5\\base\\base_page.py\", line 36, in promocode_assertion\n    raise Exception(\"Промокод применён повторно — ошибка\")\n"}, "start": 1753716638520, "stop": 1753716639096}], "start": 1753716638244, "stop": 1753716639107}], "start": 1753716612094, "stop": 1753716639111, "uuid": "16a6af52-d11f-4d26-a20a-af02390e5b1b", "historyId": "9a1d6b7309c144ad798cc97803ea4b29", "testCaseId": "9a1d6b7309c144ad798cc97803ea4b29", "fullName": "tests.test_promocode#test_04", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_promocode"}, {"name": "host", "value": "RUDSEK026290"}, {"name": "thread", "value": "381020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_promocode"}], "titlePath": ["tests", "test_promocode.py"]}